# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = swww-daemon
exec-once = ~/.config/hypr/scripts/wallpaper.sh

# exec-once = mpvpaper ALL ~/Pictures/Videos/ -o "--loop --no-audio --video-unscaled=no --panscan=1.0 --shuffle --loop-playlist"
exec-once = ~/.config/waybar/scripts/launch.sh
exec-once = hypridle
exec-once = swayosd-server
exec-once = swaync
exec-once = swaync-client -df
