# See https://wiki.hypr.land/Configuring/Monitors/


# Monitor Configuration
# monitor = name, resolution, position, scale

# External Monitor (Top)
monitor = HDMI-A-1, 1920x1080@100, 0x0, 1

# Built-in Monitor (Bottom)
# Positioned at 0x1080 because the monitor above it is 1080px tall
monitor = eDP-1, 1920x1200@60, 0x1080, 1














# # External monitor (top)
# monitor = HDMI-A-1,preferred,auto, 0.8
#
# # Built-in laptop display (bottom)
# monitor=,preferred,auto,1
#
