##### Basic Setup #####

# Set prefix key to Alt + q (instead of default Ctrl+b)
set -g prefix M-q
unbind C-b
bind M-q send-prefix

# Reload config with prefix + r
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded"

# Enable mouse support
set -g mouse on

# Enable 256-color support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Use vi-style keys in copy mode
setw -g mode-keys vi

##### Pane and Window Management #####

# Split windows and retain current working directory
bind c new-window -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Vim-style pane switching
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start window and pane indexing from 1
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

##### Status Bar #####
# Set the status bar position (top or bottom)
set-option -g status-position top

##### Plugins #####

# TPM (Tmux Plugin Manager)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

# Config Dracula Theme
set -g @dracula-plugins "cwd time"
set -g @dracula-show-powerline false
set -g @dracula-show-timezone false
set -g @dracula-time-format "%a %F %R"
set -g @dracula-show-left-icon "#h"
set -g @dracula-cwd-max-dirs "1"
set -g @dracula-cwd-max-chars "100"

# Initialize TPM
run '~/.config/tmux/plugins/tpm/tpm'
